
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/monitors.t2

# Note - use `hyprctl monitors all` to see all active / inactive monitors; put `auto` or `1` for scale


# monitor = ,preferred, auto, auto

# =========== LEFT - Laptop | RIGHT - Monitor ==============
monitor=HDMI-A-2, 1920x1080@100, 0x0, 1 # <LEFT> - PRIMARY MONITOR - External
monitor=eDP-1, 1920x1080@60, 1920x0, 1.2 # <RIGHT> - Secondary MONITOR - LAPTOP 

# =========== LEFT - Monitor | RIGHT - Laptop ==============
monitor=DP-1, 1920x1080@60, 0x0, 1
monitor=eDP-1, 1920x1080@60, 1920x0, 1.2
# =========== LEFT - Laptop | RIGHT - Monitor ================
# monitor=HDMI-A-1, 1920x1080@100, 1920x0, 1.2
# monitor=eDP-1, 1920x1080@60, 0x0, 1
